# Generated by Django 3.2 on 2023-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('1', 'Registration Issue'), ('2', 'Login Issue'), ('3', 'Payment Issue'), ('4', 'General Enquiry'), ('5', 'Product Query'), ('6', 'Report a Review')], default='4', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
                ('written_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
